### ISSUE TITLE
Provide consistent consensus names

### ISSUE THREAD

**Issue by DanielOlson** [TravisWheelerLab/ULTRA#13]
Right now, consensus names are arbitrary based on the the first letter observed. The repeat ATCATCATCATC will be named "ATC". The repeat TCATCATCATCA will be named "TCA". They have the same repetitive pattern and they should share the same name. To accomplish this, we can sort all permutations of a repeat's name and use the alphabetically smallest name (in that case, both the ATC and the TCA repeat would be named 'ATC').

**Comment by traviswheeler** [comment]
See: 
https://stackoverflow.com/questions/15002881/lexicographically-smallest-string-after-rotation/15005277#15005277
