### ISSUE TITLE
cannot make on Ubuntu

### ISSUE THREAD

**Issue by evoecogen-git** [TravisWheelerLab/ULTRA#16]
Hi,

I have managed to compile ULTRA on an M2 mac. However, I would rather use it on our server, running Ubuntu 20.04. Unfortunately 'make' results in a whole load of errors.

/media/data1/bin/ULTRA-b89df73b5644395eeafd15a328227c0f6929716c/src/repeat.hpp:64:3: note: ‘std::vector’ is defined in header ‘<vector>’; did you forget to ‘#include <vector>’?
   64 |   std::vector<std::string> *consensi;
      |   ^~~
/media/data1/bin/ULTRA-b89df73b5644395eeafd15a328227c0f6929716c/src/repeat.hpp:91:8: error: ‘vector’ in namespace ‘std’ does not name a template type
   91 |   std::vector<RepeatRegion *> *SplitRepeats(const int depth, const int cutoff);
      |        ^~~~~~
/media/data1/bin/ULTRA-b89df73b5644395eeafd15a328227c0f6929716c/src/repeat.hpp:91:3: note: ‘std::vector’ is defined in header ‘<vector>’; did you forget to ‘#include <vector>’?
   91 |   std::vector<RepeatRegion *> *SplitRepeats(const int depth, const int cutoff);
      |   ^~~
/media/data1/bin/ULTRA-b89df73b5644395eeafd15a328227c0f6929716c/src/repeat.cpp: In constructor ‘RepeatRegion::RepeatRegion()’:
/media/data1/bin/ULTRA-b89df73b5644395eeafd15a328227c0f6929716c/src/repeat.cpp:213:3: error: ‘consensi’ was not declared in this scope; did you mean ‘consensu ’?
  213 |   consensi = nullptr;
      |   ^~~~~~~~
      |   consensus
/media/data1/bin/ULTRA-b89df73b5644395eeafd15a328227c0f6929716c/src/repeat.cpp:214:3: error: ‘splits’ was not declared in this scope
  214 |   splits = nullptr;
      |   ^~~~~~
/media/data1/bin/ULTRA-b89df73b5644395eeafd15a328227c0f6929716c/src/repeat.cpp: In destructor ‘RepeatRegion::~RepeatRegion()’:
/media/data1/bin/ULTRA-b89df73b5644395eeafd15a328227c0f6929716c/src/repeat.cpp:266:7: error: ‘splits’ was not declared in this scope
  266 |   if (splits != nullptr) {
      |       ^~~~~~
/media/data1/bin/ULTRA-b89df73b5644395eeafd15a328227c0f6929716c/src/repeat.cpp:268:12: error: type ‘<type error>’ argument given to ‘delete’, expected pointer
  268 |     delete splits;
      |            ^~~~~~
/media/data1/bin/ULTRA-b89df73b5644395eeafd15a328227c0f6929716c/src/repeat.cpp:272:7: error: ‘consensi’ was not declared in this scope; did you mean ‘consensu ’?
  272 |   if (consensi != nullptr) {
      |       ^~~~~~~~
      |       consensus
/media/data1/bin/ULTRA-b89df73b5644395eeafd15a328227c0f6929716c/src/repeat.cpp:274:12: error: type ‘<type error>’ argument given to ‘delete’, expected pointer
  274 |     delete consensi;
      |            ^~~~~~~~
/media/data1/bin/ULTRA-b89df73b5644395eeafd15a328227c0f6929716c/src/repeat.cpp: At global scope:
/media/data1/bin/ULTRA-b89df73b5644395eeafd15a328227c0f6929716c/src/repeat.cpp:644:30: error: no declaration matches ‘std::vector<RepeatRegion*>* RepeatRegion::SplitRepeats(int, int)’
  644 | std::vector<RepeatRegion *> *RepeatRegion::SplitRepeats(const int depth,
      |                              ^~~~~~~~~~~~
/media/data1/bin/ULTRA-b89df73b5644395eeafd15a328227c0f6929716c/src/repeat.cpp:644:30: note: no functions named ‘std::vector<RepeatRegion*>* RepeatRegion::SplitRepeats(int, int)’
In file included from /media/data1/bin/ULTRA-b89df73b5644395eeafd15a328227c0f6929716c/src/repeat.cpp:6:
/media/data1/bin/ULTRA-b89df73b5644395eeafd15a328227c0f6929716c/src/repeat.hpp:24:7: note: ‘class RepeatRegion’ defined here
   24 | class RepeatRegion {
      |       ^~~~~~~~~~~~
make[2]: *** [CMakeFiles/ultra.dir/build.make:141: CMakeFiles/ultra.dir/src/repeat.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:104: CMakeFiles/ultra.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by DanielOlson** [comment]
Fixed - thanks!

**Comment by evoecogen-git** [comment]
Thanks!
Any chance you could also make the necessary corrections to the version outputting bed files, please (ULTRA-b89df73b5644395eeafd15a328227c0f6929716c)? Quite a useful feature.

**Comment by DanielOlson** [comment]
I’m on paternity leave right now, but our official 1.0 release (which includes BED support and has the build-fix) will be completed and pushed to our main branch in the upcoming week(s). Until then, if you encounter the error at compile time you can add “#include <vector>” to the top of src/repeat.hpp and everything will compile fine on Ubuntu. Thanks once again!

**Comment by traviswheeler** [comment]
Looks like github removed part of Daniel's comment.  It should say:   

add
`#include <vector>`
to src/repeat.hpp
