### ISSUE TITLE
Output fields unclear

### ISSUE THREAD

**Issue by CEPHAS-01** [TravisWheelerLab/ULTRA#19]
Hi,
I ran ULTRA to identify repeat models using version 0.99.17.
I got two files produced - one was the settings file while the other is a tab-delimited bed (extended) file.
I have struggled, frustratingly, to understand what each column of the bed file is. All my search for information on this has proved abortive. Here is a line from my output:

haplotype2 36141 36171 GTGCTGACCCT 6.063256 . 36141 36171 0,0,0 1 30 0

Thank you.

**Comment by DanielOlson** [comment]
Hi,
The default output is  BED format (https://genome.ucsc.edu/FAQ/FAQformat.html#format1). For most purposes, the important columns are 1 (sequence name) 2 (sequence start) 3 (sequence end) 4 (repeat pattern) 5 (repeat score). We also support json output which has more descriptive output labels.

Thanks for asking, we’ll work to provide better documentation!
