### ISSUE TITLE
ULTRA and GFF/BED

### ISSUE THREAD

**Issue by olekto** [TravisWheelerLab/ULTRA#3]
Hi,
thank you for developing ULTRA. The field certainly needed an open source tool like this.

I've just started using ULTRA, and am looking at the CSV file. Do you have a converter to GFF or BED? I'd rather not write anything myself if you have something you are using. 

Thank you.

Ole

**Comment by traviswheeler** [comment]
Ole,
We don't currently have GFF or BED output (or converter), but it's on the list. Normally, I'd say "we'll get right on it", but it's more likely to be maybe 2-4 weeks while we stay heads-down on a SARS-related project.

**Comment by Tierhon** [comment]
Thank you,
I'll try writing something myself. Is it documented somewhere? I guess I mostly need 
"Start": 4918,
"Length": 62,
"Period": 6,
and
"Consensus": "GAGAGA", and I can parse those easily enough I hope. 

If start is 4918, and length is 62, then it ends at 4918+62 = 4980?

Thank you.

Ole

**Comment by DanielOlson** [comment]
Correct - in the JSON output a repeat with "Start": 4918 and "Length": 62 is repetitive from index 4918 and up to (but not including) 4980. Right now consensus has some oddities, and although it will produce the expected result most of the time, in regions where there are connected repeats of changing pattern or many indels, the consensus pattern may be slightly off from what you’d expect. In a few weeks I’ll be working on ULTRA full time and the top of my todo list is improving the consensus results, and two other high ranking todo items are expanding output formats and providing more complete documentation.

Thanks,
Daniel

**Comment by Tierhon** [comment]
Great, then I know what I need to do.

Thank you both.

Ole

**Comment by traviswheeler** [comment]
Re-opening, since we'll need to do this (output BED format) in the near future.

**Comment by xiekunwhy** [comment]
Any progress? Can ULTRA output bed or gff3 format now?

Best,
Kun

**Comment by DanielOlson** [comment]
The 1.0-dev branch now outputs BED by default and still supports the option of JSON output. I am currently caught up in conferences, but our goal is to have an official 1.0 release of ULTRA in August. Until then, here is a dev-commit of ULTRA that supports BED output and in my (limited) testing is stable: https://github.com/TravisWheelerLab/ULTRA/tree/b89df73b5644395eeafd15a328227c0f6929716c

Daniel
