### ISSUE TITLE
repeat pattern missing

### ISSUE THREAD

**Issue by biofcallejas** [TravisWheelerLab/ULTRA#35]
Nice work!
I'm running the version 1.0.0 (beta 7) like this:
`./ultra examples/ex1.fa`

The result looks like this:
```
chr3	152	180	.	152	180	0,0,0	1	28	0
chr3	1087	1111	.	1087	1111	0,0,0	1	24	0
chr3	1262	1277	.	1262	1277	0,0,0	1	15	0
chr3	1403	1418	.	1403	1418	0,0,0	1	15	0
chr3	3087	3100	.	3087	3100	0,0,0	1	13	0
chr3	3707	3751	.	3707	3751	0,0,0	1	44	0
```
The repeat pattern sequence is missing (column 4?), is there any possibility to include it?
many thanks in advance!

**Comment by DanielOlson** [comment]
The 4th column should definitely show the repeat pattern (and it has in the past... investigating what's going on here). I'll close this thread when I fix what's happening, but in the mean time you can use JSON output (using the -j flag) which correctly shows the repetitive pattern/sequence. Thanks for finding and reporting!

Daniel Olson

**Comment by biofcallejas** [comment]
Thank you! It seems like the p-value is not included either using the `--pval` parameter (in the bed output).
