### ISSUE TITLE
the parameter -minlen is not working, v1.0.0

### ISSUE THREAD

**Issue by biofcallejas** [TravisWheelerLab/ULTRA#37]
I ran it in a for loop for `-minlen` [1000, 2000, 3000, 4000, 5000] and the result is exactly the same (version 1.0.0, beta 7). It seems like the filtering is not working.
And also I'm getting this message (warning?)

```
Could not convert: --match = inlen
Run with --help for more information.
```

**Comment by traviswheeler** [comment]
I believe the argument is --minlen  (two dashes).  When you use -minlen (one dash), it's like passing "-m inlen" ... which leads to the error you observed.

**Comment by biofcallejas** [comment]
Oh.. I see, now it's working. Thanks!
