### ISSUE TITLE
column names of the bed file?

### ISSUE THREAD

**Issue by Jigyasa3** [TravisWheelerLab/ULTRA#57]
Dear @traviswheeler @glesica @DanielOlson @jackroddy @colligant 

Thank you for a great resource in the field! I wanted to ask how to read my `bed` output file?
I understand,
V1- sample name
V2- start of repeat
V3- end of repeat
V4- repeat found (or is it consensus?)
V5- score
V6- strand
V7- start of sequence
V8- end of sequence
V9- ?
V10- ?
V11- sequence length

Here is an example of the output-
 ```
                    V1  V2  V3                      V4        V5            V6  V7  V8
1 AB237782_1__2273_2446  20  60                 AGCATAT  8.405321  .  20  60
2 AB237782_1__8188_9525 502 612 AAACGTCCGCCCCTCCAATGTTC 29.329271  . 502 612
     V9 V10 V11 V12
1 0,0,0   1  40   0
2 0,0,0   1 110   0
```
Looking forward to your reply!

**Comment by DanielOlson** [comment]
Thank you for your comment! The current beta of ULTRA uses BED 12 (https://genome.ucsc.edu/FAQ/FAQformat.html#format1). V4 is the consensus pattern, V7/V8 are "thick-start" and "thick-end" and can be safely ignored, v9 is RGB and can be safely ignored, V10 is the number of subrepeats, V11 is the lengths of subrepeats, and V12 is the starting locations of subrepeats (relative to the sequence start in V2). 

We're going to move away from BED as our default output format and instead use a custom TSV that has less bloat (and also  includes headers!) The new format will be included in the 1.0 update that will be released in the upcoming weeks. Until then, for most purposes you will likely only need columns V1-V5. 

Thanks,
Daniel Olson
