### ISSUE TITLE
does repeat number equal consensus length/period?

### ISSUE THREAD

**Issue by WeiCSong** [TravisWheelerLab/ULTRA#70]
Hi,
i found that in the output tsv there isn't a field about the exact repeat number, so i assume that this could be calculated as (end-start+1)/period, is that right? In case where indel happens, is there a more precise way to calculate? Thanks for your help.

**Comment by DanielOlson** [comment]
Using --json will allow you to see how many insertions/deletions occurred, and so you can then calculate the repeat number as (end - start + deletions - insertions) / period. That's not a very nice user experience, and ULTRA should definitely allow users to have easy access to repeat count.

I'll update ULTRA to output repeat counts later this week. I'll comment here to let you know when its done -- thanks for opening an issue!

**Comment by DanielOlson** [comment]
It took longer than I would have liked to have time for this update, but it is now in place on the main branch. Using "-c" will result in a the following columns in TSV format: #copies, #substitutions, #insertions, and #deletions.

Using -c with --json format will also yield copy count, substitutions, insertions, and deletions (additionally, substitutions, insertions, and deletions are now hidden by default when using --json).

Thank you once again for your feedback, let me know if anything else comes up!
